language: node_js
node_js:
- '4.1'
sudo: required
dist: trusty
addons:
  code_climate:
    repo_token:
      secure: DgsPCEjqSFdTjuiTah/sp7ijRj1NwIPGZu8pFVFZelxt9M+2uIuIhVT95h6K4ywf//ozMVPRM0e6rCeP5Zu50NmP3qxG7ZrFqdGejusbiXZVyGiIkZ6ssXepyIUy3g9nQGXuL2MYimh79rwIaTpLnTEabn7uigd7GAViLbGWx/UcZq7N8q0WdjYFOOJwKGlrkMFRAPMKlEymlK7m/3M6UDIgi4rv92WBuefm+sDgmLQDLxTq2pNINdRZbWB6cpEjI3utFoKYo5vPljPVyFijJ1Sud8S6QlGcZ0fA9koNKJpopVcuufASXK8kzCFTpUOIDodSnI3b5rfwj9ydAxi4WfM5iVeKmpXnariWRANbHFE/NrJwYmqm/NsO1hDTQaMg9ycoaJUCQJjkeaEiMYpP2PKQFGJ1Ag9XI268ae5aB3pXrygishswMcf5qRtrM0VXPsEOoq2wsecvY6ERfBCUwL7fLxFud4D7Yvq9K518+N525WZ3ZKg7Uq6w8VzwX5cJk2QouQ5FsEhsQR7oC8xjevnYxBfS2M++afiOoMawWXuaV2ZrPuKW2r5FpCBwlpB8fZtcsv7G34JutG/WD2BKehLR5bG78kKUbvTId0GBeNEDgjkYhKOoo03VOuIRXl2zIbd4sbp8Nm3vZNBVMMnQAmxgHNDhaSamALDL8fo9XMU=
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
- npm install -g codeclimate-test-reporter
install:
- npm install
after_script:
- codeclimate-test-reporter < ./report-lcov/lcov.info
